data = [
    {'name': 'Bruno Mars', 'follower_count': 262, 'description': 'Singer', 'country': 'USA'},
    {'name': 'David Beckham', 'follower_count': 453, 'description': 'Athlete', 'country': 'UK'},
    {'name': 'Cristiano Ronaldo', 'follower_count': 457, 'description': 'Athlete', 'country': 'Portugal'},
    {'name': 'Reese Witherspoon', 'follower_count': 94, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Johnny Depp', 'follower_count': 193, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Noah Beck', 'follower_count': 471, 'description': 'Social media star', 'country': 'USA'},
    {'name': 'Anne Hathaway', 'follower_count': 365, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Tyler The Creator', 'follower_count': 362, 'description': 'Musician', 'country': 'USA'},
    {'name': 'Selena Gomez', 'follower_count': 359, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Lisa (BLACKPINK)', 'follower_count': 204, 'description': 'Singer', 'country': 'South Korea'},
    {'name': 'Steve Harvey', 'follower_count': 477, 'description': 'Comedian', 'country': 'USA'},
    {'name': 'Tom Cruise', 'follower_count': 458, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Natalie Portman', 'follower_count': 277, 'description': 'Actor', 'country': 'Israel'},
    {'name': 'Dixie D''Amelio', 'follower_count': 213, 'description': 'Social media star', 'country': 'USA'},
    {'name': 'Post Malone', 'follower_count': 112, 'description': 'Musician', 'country': 'USA'},
    {'name': 'Rosé (BLACKPINK)', 'follower_count': 375, 'description': 'Singer', 'country': 'South Korea'},
    {'name': 'Mark Zuckerberg', 'follower_count': 284, 'description': 'Entrepreneur', 'country': 'USA'},
    {'name': 'Chris Hemsworth', 'follower_count': 144, 'description': 'Actor', 'country': 'Australia'},
    {'name': 'Jisoo (BLACKPINK)', 'follower_count': 176, 'description': 'Singer', 'country': 'South Korea'},
    {'name': 'Barack Obama', 'follower_count': 164, 'description': 'Politician', 'country': 'USA'},
    {'name': 'Ryan Reynolds', 'follower_count': 202, 'description': 'Actor', 'country': 'Canada'},
    {'name': 'Shakira', 'follower_count': 483, 'description': 'Singer', 'country': 'Colombia'},
    {'name': 'Naomi Osaka', 'follower_count': 259, 'description': 'Athlete', 'country': 'Japan'},
    {'name': 'Rihanna', 'follower_count': 484, 'description': 'Singer', 'country': 'Barbados'},
    {'name': 'Chris Pratt', 'follower_count': 297, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Millie Bobby Brown', 'follower_count': 375, 'description': 'Actor', 'country': 'UK'},
    {'name': 'Elon Musk', 'follower_count': 241, 'description': 'Entrepreneur', 'country': 'USA'},
    {'name': 'Cameron Diaz', 'follower_count': 365, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Shawn Mendes', 'follower_count': 272, 'description': 'Singer', 'country': 'Canada'},
    {'name': 'Matt Damon', 'follower_count': 496, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Stephen Curry', 'follower_count': 53, 'description': 'Athlete', 'country': 'USA'},
    {'name': 'Ariana Grande', 'follower_count': 84, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Justin Bieber', 'follower_count': 29, 'description': 'Singer', 'country': 'Canada'},
    {'name': 'Jason Momoa', 'follower_count': 425, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Kim Kardashian', 'follower_count': 337, 'description': 'Media personality', 'country': 'USA'},
    {'name': 'Robert Downey Jr.', 'follower_count': 116, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Zac Efron', 'follower_count': 245, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Kylie Jenner', 'follower_count': 494, 'description': 'Media personality', 'country': 'USA'},
    {'name': 'Nicki Minaj', 'follower_count': 368, 'description': 'Rapper', 'country': 'USA'},
    {'name': 'Shah Rukh Khan', 'follower_count': 498, 'description': 'Actor', 'country': 'India'},
    {'name': 'Gal Gadot', 'follower_count': 455, 'description': 'Actor', 'country': 'Israel'},
    {'name': 'Bella Hadid', 'follower_count': 420, 'description': 'Model', 'country': 'USA'},
    {'name': 'Lewis Hamilton', 'follower_count': 413, 'description': 'Athlete', 'country': 'UK'},
    {'name': 'Priyanka Chopra', 'follower_count': 364, 'description': 'Actor', 'country': 'India'},
    {'name': 'Gigi Hadid', 'follower_count': 452, 'description': 'Model', 'country': 'USA'},
    {'name': 'Lionel Messi', 'follower_count': 73, 'description': 'Athlete', 'country': 'Argentina'},
    {'name': 'Blake Lively', 'follower_count': 287, 'description': 'Actor', 'country': 'USA'},
    {'name': 'MrBeast', 'follower_count': 135, 'description': 'YouTuber', 'country': 'USA'},
    {'name': 'Neymar Jr.', 'follower_count': 172, 'description': 'Athlete', 'country': 'Brazil'},
    {'name': 'Asap Rocky', 'follower_count': 166, 'description': 'Rapper', 'country': 'USA'},
    {'name': 'Kendall Jenner', 'follower_count': 66, 'description': 'Model', 'country': 'USA'},
    {'name': 'Jim Carrey', 'follower_count': 355, 'description': 'Actor', 'country': 'Canada'},
    {'name': 'Margot Robbie', 'follower_count': 348, 'description': 'Actor', 'country': 'Australia'},
    {'name': 'Jennie (BLACKPINK)', 'follower_count': 378, 'description': 'Singer', 'country': 'South Korea'},
    {'name': 'Taylor Swift', 'follower_count': 51, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Zendaya', 'follower_count': 252, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Lady Gaga', 'follower_count': 394, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Addison Rae', 'follower_count': 423, 'description': 'Social media star', 'country': 'USA'},
    {'name': 'Amitabh Bachchan', 'follower_count': 406, 'description': 'Actor', 'country': 'India'},
    {'name': 'Leonardo DiCaprio', 'follower_count': 231, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Tom Hiddleston', 'follower_count': 79, 'description': 'Actor', 'country': 'UK'},
    {'name': 'Kevin Hart', 'follower_count': 127, 'description': 'Comedian', 'country': 'USA'},
    {'name': 'Khaby Lame', 'follower_count': 66, 'description': 'Social media star', 'country': 'Italy'},
    {'name': 'Doja Cat', 'follower_count': 100, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Keanu Reeves', 'follower_count': 237, 'description': 'Actor', 'country': 'Canada'},
    {'name': 'Chris Evans', 'follower_count': 158, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Emma Chamberlain', 'follower_count': 41, 'description': 'YouTuber', 'country': 'USA'},
    {'name': 'Oprah Winfrey', 'follower_count': 69, 'description': 'Media personality', 'country': 'USA'},
    {'name': 'Ranveer Singh', 'follower_count': 491, 'description': 'Actor', 'country': 'India'},
    {'name': 'Snoop Dogg', 'follower_count': 257, 'description': 'Rapper', 'country': 'USA'},
    {'name': 'James Charles', 'follower_count': 13, 'description': 'YouTuber', 'country': 'USA'},
    {'name': 'Tom Holland', 'follower_count': 299, 'description': 'Actor', 'country': 'UK'},
    {'name': 'Will Smith', 'follower_count': 345, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Ben Affleck', 'follower_count': 208, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Vin Diesel', 'follower_count': 321, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Jackie Chan', 'follower_count': 430, 'description': 'Actor', 'country': 'China'},
    {'name': 'Emma Stone', 'follower_count': 350, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Jennifer Lopez', 'follower_count': 442, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Cardi B', 'follower_count': 41, 'description': 'Rapper', 'country': 'USA'},
    {'name': 'Beyonce', 'follower_count': 461, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Drake', 'follower_count': 479, 'description': 'Rapper', 'country': 'Canada'},
    {'name': 'LeBron James', 'follower_count': 369, 'description': 'Athlete', 'country': 'USA'},
    {'name': 'Dwayne Johnson', 'follower_count': 315, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Billie Eilish', 'follower_count': 121, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Ed Sheeran', 'follower_count': 325, 'description': 'Singer', 'country': 'UK'},
    {'name': 'Serena Williams', 'follower_count': 383, 'description': 'Athlete', 'country': 'USA'},
    {'name': 'PewDiePie', 'follower_count': 447, 'description': 'YouTuber', 'country': 'Sweden'},
    {'name': 'Brad Pitt', 'follower_count': 357, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Emma Watson', 'follower_count': 151, 'description': 'Actor', 'country': 'UK'},
    {'name': 'Travis Scott', 'follower_count': 302, 'description': 'Rapper', 'country': 'USA'},
    {'name': 'Salman Khan', 'follower_count': 154, 'description': 'Actor', 'country': 'India'},
    {'name': 'Katy Perry', 'follower_count': 497, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Deepika Padukone', 'follower_count': 349, 'description': 'Actor', 'country': 'India'},
    {'name': 'Simone Biles', 'follower_count': 21, 'description': 'Athlete', 'country': 'USA'},
    {'name': 'Sarah Jessica Parker', 'follower_count': 388, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Miley Cyrus', 'follower_count': 295, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Charli DAmelio', 'follower_count': 361, 'description': 'Social media star', 'country': 'USA'},
    {'name': 'Hugh Jackman', 'follower_count': 424, 'description': 'Actor', 'country': 'Australia'},
    {'name': 'Kourtney Kardashian', 'follower_count': 383, 'description': 'Media personality', 'country': 'USA'},
    {'name': 'Bad Bunny', 'follower_count': 437, 'description': 'Singer', 'country': 'Puerto Rico'}
]